"""empty message

Revision ID: 592b97504a63
Revises: fe81c5137761
Create Date: 2022-01-11 16:02:28.577282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592b97504a63'
down_revision = 'fe81c5137761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards_rent_br', sa.Column('views_info', sa.Integer(), nullable=True))
    op.add_column('cards_rent_land', sa.Column('views_info', sa.Integer(), nullable=True))
    op.add_column('cards_sell_br', sa.Column('views_info', sa.Integer(), nullable=True))
    op.add_column('cards_sell_land', sa.Column('views_info', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards_sell_land', 'views_info')
    op.drop_column('cards_sell_br', 'views_info')
    op.drop_column('cards_rent_land', 'views_info')
    op.drop_column('cards_rent_br', 'views_info')
    # ### end Alembic commands ###
