"""empty message

Revision ID: c806093a58b9
Revises: 592b97504a63
Create Date: 2022-01-21 03:38:52.987124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c806093a58b9'
down_revision = '592b97504a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards_rent_br', sa.Column('description', sa.String(), nullable=True))
    op.add_column('cards_rent_land', sa.Column('description', sa.String(), nullable=True))
    op.add_column('cards_sell_br', sa.Column('description', sa.String(), nullable=True))
    op.add_column('cards_sell_land', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards_sell_land', 'description')
    op.drop_column('cards_sell_br', 'description')
    op.drop_column('cards_rent_land', 'description')
    op.drop_column('cards_rent_br', 'description')
    # ### end Alembic commands ###
