"""empty message

Revision ID: fe81c5137761
Revises: db6e8819c327
Create Date: 2022-01-11 10:12:23.398506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe81c5137761'
down_revision = 'db6e8819c327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards_rent_br', sa.Column('link_obj', sa.String(), nullable=True))
    op.add_column('cards_rent_land', sa.Column('link_obj', sa.String(), nullable=True))
    op.add_column('cards_sell_br', sa.Column('link_obj', sa.String(), nullable=True))
    op.add_column('cards_sell_land', sa.Column('link_obj', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards_sell_land', 'link_obj')
    op.drop_column('cards_sell_br', 'link_obj')
    op.drop_column('cards_rent_land', 'link_obj')
    op.drop_column('cards_rent_br', 'link_obj')
    # ### end Alembic commands ###
